module-name: eventing
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/eventing-manager:v20231025-e0419d5e
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
    - "/hack/**"
